# Generated by Django 4.2.20 on 2025-04-18 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product', max_length=255)),
                ('product_category', models.CharField(help_text='Category of the product', max_length=100)),
                ('product_image', models.CharField(help_text='Path to the product image', max_length=255)),
                ('product_selling_price', models.DecimalField(decimal_places=2, help_text='Current selling price of the product', max_digits=10)),
                ('product_description', models.TextField(help_text='Detailed description of the product')),
                ('total_returns', models.PositiveIntegerField(default=0, help_text='Total number of product returns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, help_text='Base cost of the product', max_digits=10)),
                ('confirmation_fees', models.DecimalField(decimal_places=2, default=0, help_text='Fees related to confirming product orders', max_digits=10)),
                ('packaging_fees', models.DecimalField(decimal_places=2, default=0, help_text='Fees related to packaging the product', max_digits=10)),
                ('return_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costs associated with product returns', max_digits=10)),
                ('ads_cost', models.DecimalField(decimal_places=2, default=0, help_text='Advertising costs for the product', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='The product associated with these costs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at which the product was sold', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of products in this order')),
                ('discount', models.BooleanField(default=False, help_text='Whether a discount was applied to this order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders_list', to='products.product')),
            ],
        ),
    ]
