# Generated by Django 4.2.20 on 2025-04-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveredorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivered Order', 'verbose_name_plural': 'Delivered Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcost',
            options={'verbose_name': 'Product Cost', 'verbose_name_plural': 'Product Costs'},
        ),
        migrations.AlterField(
            model_name='deliveredorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was recorded'),
        ),
        migrations.AlterField(
            model_name='deliveredorder',
            name='product',
            field=models.ForeignKey(help_text='The product this order is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders_list', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated'),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
