# Generated by Django 4.2.20 on 2025-04-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('communication', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dev', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fixed Costs',
                'verbose_name_plural': 'Fixed Costs',
            },
        ),
    ]
