# Generated by Django 4.2.20 on 2025-04-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixed_costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcosts',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Fixed Costs', 'verbose_name_plural': 'Fixed Costs'},
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='communication',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly communication expenses (internet, phone, etc.) in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the fixed costs record was created.'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='dev',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly development and maintenance costs in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='employees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly employee salary and related costs in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other monthly fixed expenses not categorized above, in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='rental',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rental expenses in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='transportation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly transportation costs in currency units.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the fixed costs record was last updated.'),
        ),
        migrations.AlterField(
            model_name='fixedcosts',
            name='user',
            field=models.OneToOneField(help_text='The user associated with these fixed costs. One-to-one relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to=settings.AUTH_USER_MODEL),
        ),
    ]
